name: 'schedule'

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Shanghai

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@main
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: |
          node index.js
          git add .
          git commit -m "update by github action"
          git push
        env:
          U_MAIL: ${{ secrets.U_MAIL }}
          U_PASSWORD: ${{ secrets.U_PASSWORD }}
